services:
  # Flask App
  myflaskwebservice:
    container_name: myflaskwebservice
    build: .
    ports:
      - "17000:5000"
    volumes:
      - .:/usr/src/app

  # Kong API gateway
  kong:
    image: kong:3.1.1-ubuntu
    container_name: kong-dbless
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: always
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    volumes:
      - .:/kong/declarative/

  # Splunk Enterprise server
  splunk-kong:
    image: splunk/splunk:latest
    container_name: splunk-kong
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_HEC_TOKEN=00000000-0000-0000-0000-0000000000000
      - SPLUNK_PASSWORD=changeme
    ports:
      - 18000:8000
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:8000' ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./splunk.yml:/tmp/defaults/default.yml
      - /opt/splunk/var
      - /opt/splunk/etc
    depends_on:
      - kong

  # OpenTelemetry Collector
  otelcollector-kong:
    image: quay.io/signalfx/splunk-otel-collector:0.71.0
    container_name: otelcollector-kong
    command: ["--config=/etc/otel-collector-config.yml", "--set=service.telemetry.logs.level=debug"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
      - ./logs:/logs
      - ./checkpoint:/checkpoint
    depends_on:
      splunk-kong:
        condition: service_healthy